version: 2.1

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - run-tests:
          filters:
            branches:
              only:
                - main
          requires:
            - build
      - deploy:
          filters:
            branches:
              only:
                - main
          requires:
            - run-tests

jobs:
  build:
    working_directory: ~/coin-quest-app
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          name: update-npm
          command: 'sudo npm install -g npm@8.1.4'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: docker-login
          command: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run:
          name: build-docker-image
          command: docker build -t $IMAGE_NAME:latest .
      - run:
          name: publish-docker-image
          command: docker push $IMAGE_NAME

  run-tests:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-deps
          command: npm ci
      - run:
          name: run-tests
          command: npm test
      

  deploy:
    docker:
      - image: circleci/node:latest
    steps:
      - run:
          name: deploy-application
          command: ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_PUBLIC_DNS "export SERVER=\"$SERVER\"; export PRIVATE_KEY=\"$PRIVATE_KEY\"; rm -rf DevOpsProject23/; git clone https://github.com/CloByrne/DevOpsProject23.git; ls; cd DevOpsProject23; ls; source deploy.sh"
#deployment successful
